const {PermissionFlagsBits}=require('discord.js');
const {RISK}=require('./engine');
const {NethrionError,CODES}=require('../observability/errors');
const {resolveRole,resolveMember}=require('../resolvers/entities');
class DiscordActionService{
  constructor({engine,permissions,repos,analytics,logger}){this.engine=engine;this.permissions=permissions;this.repos=repos;this.analytics=analytics;this.logger=logger;}
  assignRole(ctx){return this._roleAction(ctx,'assign_role',false);}
  setServerMode(ctx){const modes=new Set(['NORMAL','EVENT','MAINTENANCE','SMP_MAINTENANCE','RAID_PROTECTION','EMERGENCY']);return this.engine.run(ctx,{toolName:'set_server_mode',intent:'change server mode',risk:RISK.HIGH,preflight:async()=>{if(!modes.has(ctx.args.mode))throw new NethrionError(CODES.INVALID_TOOL_ARGS,'Invalid server mode.');if(ctx.guild.ownerId!==ctx.member.id&&!ctx.member.permissions.has(PermissionFlagsBits.ManageGuild))throw new NethrionError(CODES.MISSING_PERMISSION,'Manage Server permission required.');const previous=this.repos.getGuildSettings(ctx.guild.id)?.mode||'NORMAL';return {target:{guildId:ctx.guild.id,guildName:ctx.guild.name},changes:[`Set server mode to ${ctx.args.mode}`],precondition:{previous}};},execute:async()=>{this.repos.updateGuildSettings(ctx.guild.id,{mode:ctx.args.mode});this.analytics.event(ctx.guild.id,'mode_changed',ctx.member.id,{mode:ctx.args.mode});return {mode:ctx.args.mode};},verify:async()=>({verified:(this.repos.getGuildSettings(ctx.guild.id)?.mode===ctx.args.mode)})});}

  _roleAction(ctx,toolName,remove){const {guild,member,args}=ctx;return this.engine.run(ctx,{toolName,intent:remove?'remove role':'assign role',risk:RISK.MEDIUM,preflight:async()=>{const target=resolveMember(guild,args.user_id);if(!target.value)throw new NethrionError(target.candidates?.length?CODES.AMBIGUOUS_TARGET:CODES.INVALID_TARGET,target.candidates?.length?'Member is ambiguous. Please choose an exact user.':'Member not found.',{candidates:target.candidates?.map(x=>({id:x.id,name:x.user.username}))});const rr=resolveRole(guild,args.role_query);if(!rr.value)throw new NethrionError(rr.candidates?.length?CODES.AMBIGUOUS_TARGET:CODES.INVALID_TARGET,rr.candidates?.length?'Role is ambiguous. Please choose an exact role.':'Role not found.',{candidates:rr.candidates?.map(x=>({id:x.id,name:x.name}))});const role=rr.value;this.permissions.checkActionAuthorization({member,guild,action:{requiredPermission:PermissionFlagsBits.ManageRoles},targetRole:role});const already=target.value.roles.cache.has(role.id);return {target:{memberId:target.value.id,member:target.value.user.username,roleId:role.id,role:role.name},changes:[`${remove?'Remove':'Add'} ${role.name} ${remove?'from':'to'} ${target.value.user.username}`],permission:{targetRole:role.id},precondition:{already}};},execute:async()=>{const target=resolveMember(guild,args.user_id).value;const role=resolveRole(guild,args.role_query).value;if(remove)await target.roles.remove(role,`NETHRION action by ${member.user.username}`);else await target.roles.add(role,`NETHRION action by ${member.user.username}`);return {memberId:target.id,roleId:role.id,removed:remove};},verify:async()=>{const target=await guild.members.fetch(args.user_id).catch(()=>null);const role=resolveRole(guild,args.role_query).value;const hasNow=Boolean(target&&role&&target.roles.cache.has(role.id));return {verified:remove?!hasNow:hasNow};}});}
  lockChannel(ctx){return this._lock(ctx,true);}
  unlockChannel(ctx){return this._lock(ctx,false);}
  _lock(ctx,lock){const {guild,member,args,message}=ctx;const channel=guild.channels.cache.get(String(args.channel_id||message.channel.id));return this.engine.run(ctx,{toolName:lock?'lock_channel':'unlock_channel',intent:lock?'lock channel':'unlock channel',risk:RISK.HIGH,preflight:async()=>{if(!channel?.permissionOverwrites?.edit)throw new NethrionError(CODES.INVALID_TARGET,'Channel not found or cannot be changed.');if(!member.permissions.has(PermissionFlagsBits.ManageChannels)&&!member.permissions.has(PermissionFlagsBits.Administrator)&&guild.ownerId!==member.id)throw new NethrionError(CODES.MISSING_PERMISSION,'Manage Channels permission required.');const old=channel.permissionOverwrites.cache.get(guild.roles.everyone.id);const previous={deny:Boolean(old?.deny?.has(PermissionFlagsBits.SendMessages)),allow:Boolean(old?.allow?.has(PermissionFlagsBits.SendMessages))};return {target:{channelId:channel.id,name:channel.name},changes:[`${lock?'Deny':'Allow'} Send Messages for @everyone`],precondition:{channelId:channel.id,previous}};},execute:async()=>{await channel.permissionOverwrites.edit(guild.roles.everyone,{SendMessages:lock?false:null},{reason:`NETHRION action by ${member.user.username}`});return {channelId:channel.id,locked:lock};},verify:async()=>{const current=channel.permissionOverwrites.cache.get(guild.roles.everyone.id);const deny=Boolean(current?.deny?.has(PermissionFlagsBits.SendMessages));return {verified:lock?deny:!deny};}});}
  purgeMessages(ctx){const {guild,member,args,message}=ctx;const channel=guild.channels.cache.get(String(args.channel_id||message.channel.id));return this.engine.run(ctx,{toolName:'purge_messages',intent:'purge messages',risk:RISK.HIGH,preflight:async()=>{if(!channel?.messages?.fetch)throw new NethrionError(CODES.INVALID_TARGET,'Channel not found or cannot be purged.');if(!member.permissions.has(PermissionFlagsBits.ManageMessages)&&!member.permissions.has(PermissionFlagsBits.Administrator)&&guild.ownerId!==member.id)throw new NethrionError(CODES.MISSING_PERMISSION,'Manage Messages permission required.');const amount=Math.max(1,Math.min(100,Number(args.amount)||1));return {target:{channelId:channel.id,name:channel.name},changes:[`Delete up to ${amount} recent messages from #${channel.name}`],sideEffects:['Deleted Discord messages cannot be recovered by NETHRION.'],precondition:{amount}};},execute:async()=>{const amount=Math.max(1,Math.min(100,Number(args.amount)||1));const deleted=await channel.bulkDelete(amount,true);return {channelId:channel.id,deleted:deleted.size,requested:amount};},verify:async(ctx,result)=>({verified:Number.isInteger(result.deleted)&&result.deleted>=0&&result.deleted<=result.requested})});}
  deleteChannel(ctx){const {guild,member,args}=ctx;const channel=guild.channels.cache.get(String(args.channel_id));return this.engine.run(ctx,{toolName:'delete_channel',intent:'delete channel',risk:RISK.CRITICAL,preflight:async()=>{if(!channel)throw new NethrionError(CODES.INVALID_TARGET,'Channel not found.');if(!member.permissions.has(PermissionFlagsBits.ManageChannels)&&!member.permissions.has(PermissionFlagsBits.Administrator)&&guild.ownerId!==member.id)throw new NethrionError(CODES.MISSING_PERMISSION,'Manage Channels permission required.');return {target:{channelId:channel.id,name:channel.name},changes:[`Delete #${channel.name}`],sideEffects:['The channel and its Discord-visible history will no longer be available.']};},execute:async()=>{await channel.delete(`NETHRION action by ${member.user.username}`);return {channelId:channel.id,deleted:true};},verify:async()=>({verified:!guild.channels.cache.has(channel.id)})});}
  async undo(ctx,actionId){const p=this.engine.assertExecuted(actionId,ctx.guild.id,ctx.member.id);const plan=JSON.parse(p.plan_json);const canManage=ctx.guild.ownerId===ctx.member.id||ctx.member.permissions.has(PermissionFlagsBits.ManageGuild)||ctx.member.permissions.has(PermissionFlagsBits.Administrator);if(!canManage)return {state:'BLOCKED',code:CODES.MISSING_PERMISSION,message:'Manage Server permission required to undo an action.'};if(!['assign_role','lock_channel','unlock_channel','set_server_mode'].includes(plan.toolName))return {state:'BLOCKED',code:'NOT_REVERSIBLE',message:'That action is not reversible through NETHRION.'};if(plan.toolName==='assign_role'){if(plan.precondition?.already){this.repos.addAudit({guildId:ctx.guild.id,actionId:`undo:${actionId}`,actorId:ctx.member.id,request:`undo ${actionId}`,resolvedIntent:'undo role action',toolName:'undo_action',target:plan.target,resultState:'SUCCESS'});this.engine.markReverted(actionId);return {state:'SUCCESS',message:'Nothing changed during undo because the member already had that role.'};}const member=await ctx.guild.members.fetch(plan.target.memberId).catch(()=>null);const role=ctx.guild.roles.cache.get(plan.target.roleId);if(!member||!role)return {state:'UNKNOWN',code:CODES.INVALID_TARGET,message:'The original member or role is no longer available.'};this.permissions.checkActionAuthorization({member:ctx.member,guild:ctx.guild,action:{requiredPermission:PermissionFlagsBits.ManageRoles},targetRole:role});await member.roles.remove(role,`NETHRION undo ${actionId}`);this.engine.markReverted(actionId);return {state:'SUCCESS',message:'Role assignment was reverted.'};}
    if(plan.toolName==='set_server_mode'){this.repos.updateGuildSettings(ctx.guild.id,{mode:plan.precondition?.previous||'NORMAL'});this.engine.markReverted(actionId);return {state:'SUCCESS',message:'Server mode was reverted.'};}
    const channel=ctx.guild.channels.cache.get(plan.target.channelId);if(!channel)return {state:'UNKNOWN',code:CODES.INVALID_TARGET,message:'The original channel is no longer available.'};if(!ctx.member.permissions.has(PermissionFlagsBits.ManageChannels)&&!ctx.member.permissions.has(PermissionFlagsBits.Administrator)&&ctx.guild.ownerId!==ctx.member.id)throw new NethrionError(CODES.MISSING_PERMISSION,'Manage Channels permission required to undo a channel action.');const prev=plan.precondition?.previous||{};const value=prev.allow?true:(prev.deny?false:null);await channel.permissionOverwrites.edit(ctx.guild.roles.everyone,{SendMessages:value},{reason:`NETHRION undo ${actionId}`});this.engine.markReverted(actionId);const current=channel.permissionOverwrites.cache.get(ctx.guild.roles.everyone.id);const deny=Boolean(current?.deny?.has(PermissionFlagsBits.SendMessages));const verified=prev.deny?deny:(prev.allow?!deny:!deny);if(!verified)throw new NethrionError(CODES.VERIFY_FAILED,'Undo was applied but could not be verified.');return {state:'SUCCESS',message:'Channel permission change was reverted.'};}
}
module.exports={DiscordActionService};
