const crypto=require('node:crypto');
const {CODES,NethrionError,normalizeError}=require('../observability/errors');
const RISK={LOW:'LOW',MEDIUM:'MEDIUM',HIGH:'HIGH',CRITICAL:'CRITICAL'};
const needsConfirmation=r=>r===RISK.HIGH||r===RISK.CRITICAL;
class ActionEngine{
  constructor({db,repos,logger,ttlSeconds=120}){this.db=db;this.repos=repos;this.logger=logger;this.ttlSeconds=ttlSeconds;}
  modeAllows(guild,member,spec){const mode=this.repos.getGuildSettings(guild.id)?.mode||'NORMAL';if(mode==='EMERGENCY'&&spec.risk!==RISK.LOW&&guild.ownerId!==member.id&&!member.permissions?.has?.('Administrator'))return false;if(mode==='RAID_PROTECTION'&&['assign_role','delete_channel'].includes(spec.toolName)&&guild.ownerId!==member.id)return false;return true;}
  async run(ctx,spec){const actionId=ctx.actionId||spec.actionId||crypto.randomUUID();let permission={};try{
      if(!this.modeAllows(ctx.guild,ctx.member,spec))throw new NethrionError(CODES.MISSING_PERMISSION,'The current server mode blocks this action for this actor.');
      const preflight=await spec.preflight(ctx);permission=preflight.permission||{};
      const plan={actionId,guildId:ctx.guild.id,actorId:ctx.member.id,toolName:spec.toolName,risk:spec.risk,args:ctx.args||{},target:preflight.target||{},changes:preflight.changes||[],sideEffects:preflight.sideEffects||[],precondition:preflight.precondition||null};
      if(needsConfirmation(spec.risk)&&!ctx.confirm){const expiresAt=new Date(Date.now()+this.ttlSeconds*1000).toISOString();this.db.prepare(`INSERT OR REPLACE INTO action_plans(action_id,guild_id,actor_id,tool_name,risk,plan_json,expires_at,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(actionId,ctx.guild.id,ctx.member.id,spec.toolName,spec.risk,JSON.stringify(plan),expiresAt,'PENDING',new Date().toISOString());this.repos.addAudit({guildId:ctx.guild.id,actionId,actorId:ctx.member.id,request:ctx.request,resolvedIntent:spec.intent,toolName:spec.toolName,target:plan.target,permission,resultState:'BLOCKED',errorCode:CODES.CONFIRMATION_REQUIRED});return {state:'BLOCKED',code:CODES.CONFIRMATION_REQUIRED,actionId,plan,expiresAt};}
      if(ctx.confirm){const stored=this.assertConfirmation(actionId,ctx.guild.id,ctx.member.id);const storedPlan=JSON.parse(stored.plan_json);if(storedPlan.toolName!==spec.toolName)throw new NethrionError(CODES.STALE_PLAN,'That action plan no longer matches this operation.');if(JSON.stringify(storedPlan.target)!==JSON.stringify(plan.target))throw new NethrionError(CODES.STALE_PLAN,'The target changed since the preview. Please preview again.');}
      const result=await spec.execute(ctx,preflight);const verify=spec.verify?await spec.verify(ctx,result,preflight):{verified:true};if(!verify.verified)throw new NethrionError(CODES.VERIFY_FAILED,'The action request was sent, but the resulting state could not be verified.',{verify});
      const now=new Date().toISOString();this.db.prepare(`INSERT OR REPLACE INTO action_plans(action_id,guild_id,actor_id,tool_name,risk,plan_json,expires_at,status,created_at,verified_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(actionId,ctx.guild.id,ctx.member.id,spec.toolName,spec.risk,JSON.stringify(plan),new Date(Date.now()+this.ttlSeconds*1000).toISOString(),'EXECUTED',now,now);
      this.repos.addAudit({guildId:ctx.guild.id,actionId,actorId:ctx.member.id,request:ctx.request,resolvedIntent:spec.intent,toolName:spec.toolName,target:plan.target,permission,resultState:'SUCCESS'});this.repos.recordAnalytics(ctx.guild.id,'action_executed',ctx.member.id,{toolName:spec.toolName,actionId});return {state:'SUCCESS',actionId,result,verified:verify,plan};
    }catch(err){const e=normalizeError(err);this.logger.warn(spec.toolName,e.code,e.message);this.repos.addAudit({guildId:ctx.guild.id,actionId,actorId:ctx.member.id,request:ctx.request,resolvedIntent:spec.intent,toolName:spec.toolName,target:{},permission,resultState:e.code===CODES.CONFIRMATION_REQUIRED?'BLOCKED':'FAILED',errorCode:e.code});return {state:e.code===CODES.CONFIRMATION_REQUIRED?'BLOCKED':'FAILED',actionId,code:e.code,message:e.message,meta:e.meta};}}
  assertExecuted(actionId,guildId,actorId){const p=this.db.prepare(`SELECT * FROM action_plans WHERE action_id=? AND guild_id=? AND actor_id=?`).get(actionId,guildId,actorId);if(!p)throw new NethrionError(CODES.INVALID_TARGET,'Action not found.');if(p.status!=='EXECUTED')throw new NethrionError(CODES.STALE_PLAN,'Only an executed action can be reverted.');return p;}
  markReverted(actionId){const row=this.db.prepare(`SELECT guild_id,actor_id FROM action_plans WHERE action_id=?`).get(actionId);if(!row)throw new NethrionError(CODES.INVALID_TARGET,'Action not found.');this.db.prepare(`UPDATE action_plans SET status='REVERTED' WHERE action_id=?`).run(actionId);this.repos.recordAnalytics(row.guild_id,'action_reverted',row.actor_id,{actionId});}
  assertConfirmation(actionId,guildId,actorId){const p=this.db.prepare(`SELECT * FROM action_plans WHERE action_id=? AND guild_id=? AND actor_id=?`).get(actionId,guildId,actorId);if(!p)throw new NethrionError(CODES.CONFIRMATION_EXPIRED,'Confirmation plan not found or already used.');if(p.status!=='PENDING')throw new NethrionError(CODES.STALE_PLAN,'This action plan is no longer pending.');if(Date.parse(p.expires_at)<Date.now()){this.db.prepare(`UPDATE action_plans SET status='EXPIRED' WHERE action_id=?`).run(actionId);throw new NethrionError(CODES.CONFIRMATION_EXPIRED,'That confirmation expired. Please preview the action again.');}return p;}
}
module.exports={ActionEngine,RISK,needsConfirmation};
