const http=require('node:http');
function escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function readBody(req){return new Promise((resolve,reject)=>{let b='';req.on('data',x=>{b+=x;if(b.length>100000)req.destroy();});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject);});}
class DashboardServer{
 constructor({config,services,logger}){this.config=config;this.services=services;this.logger=logger;this.server=null;}
 authorized(req){if(this.config.dashboardToken)return req.headers.authorization===`Bearer ${this.config.dashboardToken}`;return ['127.0.0.1','localhost','::1'].includes(this.config.dashboardHost);}
 start(){if(!this.config.features.dashboard||this.server)return;const loopback=['127.0.0.1','localhost','::1'].includes(this.config.dashboardHost);if(!loopback&&!this.config.dashboardToken){this.logger.warn('Dashboard disabled: set DASHBOARD_TOKEN before exposing it beyond loopback.');return;}this.server=http.createServer(async(req,res)=>{try{if(!this.authorized(req)){res.writeHead(401);return res.end('Unauthorized');}const guild=this.services._client?.guilds?.cache?.get(this.config.guildId)||this.services._client?.guilds?.cache?.first?.();if(req.method==='GET'&&req.url==='/api/state'){const s=guild?this.services.repos.getGuildSettings(guild.id):null;const payload={guild:guild?{id:guild.id,name:guild.name}:null,settings:s?{mode:s.mode,timezone:s.timezone,features:s.featureFlags,channels:s.channels,roles:s.roles}:null,health:guild?await this.services.health.snapshot(guild):[]};res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify(payload));}
 if(req.method==='POST'&&req.url==='/api/config'){if(!guild){res.writeHead(400);return res.end('No guild connected.');}const body=await readBody(req);const current=this.services.repos.getGuildSettings(guild.id)||{};const patch={};if(body.mode){if(!['NORMAL','EVENT','MAINTENANCE','SMP_MAINTENANCE','RAID_PROTECTION','EMERGENCY'].includes(body.mode))throw new Error('Invalid mode.');patch.mode=body.mode;}if(body.timezone)patch.timezone=String(body.timezone).slice(0,64);if(body.channels&&typeof body.channels==='object')patch.channels={...(current.channels||{}),...Object.fromEntries(Object.entries(body.channels).filter(([k,v])=>/^[A-Za-z0-9_]+$/.test(k)&&typeof v==='string'&&v.length<=64))};if(body.roles&&typeof body.roles==='object')patch.roles={...(current.roles||{}),...Object.fromEntries(Object.entries(body.roles).filter(([k,v])=>/^[A-Za-z0-9_]+$/.test(k)&&typeof v==='string'&&v.length<=64))};if(body.feature && typeof body.feature.name==='string' && typeof body.feature.enabled==='boolean'){const allowed=new Set(Object.keys(this.config.features));if(!allowed.has(body.feature.name))throw new Error('Unknown feature flag.');patch.featureFlags={...(current.featureFlags||{}),[body.feature.name]:body.feature.enabled};}this.services.repos.updateGuildSettings(guild.id,patch);this.services.analytics.event(guild.id,'dashboard_config_changed',guild.ownerId,{keys:Object.keys(patch)});res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({ok:true,settings:this.services.repos.getGuildSettings(guild.id)}));}
 if(req.url!=='/'){res.writeHead(302,{Location:'/'});return res.end();}const rows=guild?await this.services.health.snapshot(guild):[];const audits=guild?this.services.db.prepare(`SELECT timestamp,tool_name,result_state,error_code FROM audit_events WHERE guild_id=? ORDER BY id DESC LIMIT 20`).all(guild.id):[];const s=guild?this.services.repos.getGuildSettings(guild.id):null;const html=`<!doctype html><meta charset="utf-8"><title>NETHRION Control Center</title><style>body{font-family:system-ui;margin:40px;max-width:1000px}pre{white-space:pre-wrap}table{border-collapse:collapse}td,th{padding:6px 10px;border:1px solid #ddd;text-align:left}</style><h1>NETHRION Control Center</h1><p>Guild: <b>${escape(guild?.name||'not connected')}</b></p><p>Mode: <b>${escape(s?.mode||'NO GUILD')}</b></p><h2>Health</h2><pre>${escape(JSON.stringify(rows,null,2))}</pre><h2>Recent audit</h2><table><tr><th>Time</th><th>Tool</th><th>State</th><th>Error</th></tr>${audits.map(a=>`<tr><td>${escape(a.timestamp)}</td><td>${escape(a.tool_name)}</td><td>${escape(a.result_state)}</td><td>${escape(a.error_code||'')}</td></tr>`).join('')}</table><h2>Configuration API</h2><pre>GET /api/state\nPOST /api/config JSON</pre>`;res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(html);}catch(e){this.logger.error('Dashboard request failed',e);res.writeHead(400);res.end(escape(e.message||'Request failed'));}});this.server.listen(this.config.dashboardPort,this.config.dashboardHost,()=>this.logger.info(`Dashboard listening on http://${this.config.dashboardHost}:${this.config.dashboardPort}`));}
 stop(){this.server?.close();this.server=null;}
}
module.exports={DashboardServer};
