const {SlashCommandBuilder}=require('discord.js');
function buildCommands(){return [new SlashCommandBuilder().setName('nethrion').setDescription('NETHRION community and server operations')
  .addSubcommand(s=>s.setName('ask').setDescription('Ask NETHRION').addStringOption(o=>o.setName('question').setDescription('Question or request').setRequired(true)))
  .addSubcommand(s=>s.setName('smp').setDescription('Check current Minecraft state'))
  .addSubcommand(s=>s.setName('ip').setDescription('Show Java and Bedrock connection details'))
  .addSubcommand(s=>s.setName('health').setDescription('Show subsystem health'))
  .addSubcommand(s=>s.setName('overview').setDescription('Show the current server overview'))
  .addSubcommand(s=>s.setName('recap').setDescription('Summarize recent meaningful events').addIntegerOption(o=>o.setName('hours').setDescription('Hours to review').setMinValue(1).setMaxValue(168)))
  .addSubcommand(s=>s.setName('analytics').setDescription('Show recent activity metrics').addIntegerOption(o=>o.setName('days').setDescription('Days to review').setMinValue(1).setMaxValue(90)))
  .addSubcommand(s=>s.setName('ticket').setDescription('Open a private support ticket'))
  .addSubcommand(s=>s.setName('close-ticket').setDescription('Close the current ticket'))
  .addSubcommand(s=>s.setName('suggest').setDescription('Submit a suggestion').addStringOption(o=>o.setName('idea').setDescription('Suggestion').setRequired(true)))
  .addSubcommand(s=>s.setName('report').setDescription('Report a member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(true)))
  .addSubcommand(s=>s.setName('role').setDescription('Assign a role').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('role').setDescription('Role name or ID').setRequired(true)))
  .addSubcommand(s=>s.setName('lock').setDescription('Lock the current channel'))
  .addSubcommand(s=>s.setName('unlock').setDescription('Unlock the current channel'))
  .addSubcommand(s=>s.setName('purge').setDescription('Delete recent messages').addIntegerOption(o=>o.setName('amount').setDescription('1-100').setMinValue(1).setMaxValue(100).setRequired(true)))
  .addSubcommand(s=>s.setName('backup').setDescription('Create a server backup'))
  .addSubcommand(s=>s.setName('mode').setDescription('Set server mode').addStringOption(o=>o.setName('mode').setDescription('Server mode').setRequired(true).addChoices(...['NORMAL','EVENT','MAINTENANCE','SMP_MAINTENANCE','RAID_PROTECTION','EMERGENCY'].map(x=>({name:x,value:x})))))
  .addSubcommand(s=>s.setName('undo').setDescription('Undo a recent reversible NETHRION action').addStringOption(o=>o.setName('action_id').setDescription('Action ID').setRequired(true)))
  .addSubcommand(s=>s.setName('control').setDescription('Owner control center'))
  .addSubcommand(s=>s.setName('diagnose').setDescription('Diagnose configuration and health'))
  .setDMPermission(false)];}
module.exports={buildCommands};
