const { NethrionError,CODES } = require('../observability/errors');
async function fetchJson(url,timeoutMs){const ac=new AbortController();const t=setTimeout(()=>ac.abort(),timeoutMs);try{const res=await fetch(url,{signal:ac.signal,headers:{accept:'application/json'}});if(!res.ok)throw new Error(`HTTP ${res.status}`);return await res.json();}catch(e){if(e.name==='AbortError')throw new NethrionError(CODES.EXTERNAL_TIMEOUT,'Minecraft status provider timed out.');throw e;}finally{clearTimeout(t);}}
function normalizeProviderResponse(raw,{edition,host,port,source}){const base={edition,host,port,source,checkedAt:new Date().toISOString()};if(!raw||typeof raw!=='object')return {...base,status:'UNKNOWN',error:'MALFORMED_RESPONSE'};if(raw.online===false)return {...base,status:'OFFLINE',playersOnline:0,playersMax:0,version:raw.version||null};const online=raw.players?.online,max=raw.players?.max;if(raw.online===true||Number.isFinite(online))return {...base,status:'ONLINE',playersOnline:Number.isFinite(online)?online:0,playersMax:Number.isFinite(max)?max:null,version:typeof raw.version==='string'?raw.version:raw.version?.name||null};return {...base,status:'UNKNOWN',error:'MISSING_ONLINE_FIELD'};}
class MinecraftService{
 constructor({config,db,logger}){this.config=config;this.db=db;this.logger=logger;}
 async checkEdition(guildId,edition,host,port){const started=Date.now();const base=this.config.mcStatusProviderUrl.replace(/\/$/,'');const url=`${base}/${encodeURIComponent(host)}${port?`:${encodeURIComponent(port)}`:''}`;try{const raw=await fetchJson(url,this.config.mcStatusTimeoutMs);const normalized=normalizeProviderResponse(raw,{edition,host,port,source:'mcsrvstat.us'});normalized.latencyMs=Date.now()-started;this.record(guildId,normalized,raw);return normalized;}catch(e){const status={edition,status:'UNKNOWN',host,port,source:'mcsrvstat.us',checkedAt:new Date().toISOString(),latencyMs:Date.now()-started,error:e.code||e.message};this.record(guildId,status,null);return status;}}
 record(guildId,s,raw){const previous=this.db.prepare(`SELECT status FROM smp_status WHERE guild_id=? AND edition=? ORDER BY id DESC LIMIT 1`).get(guildId,s.edition);if(previous&&previous.status!==s.status&&((previous.status==='ONLINE'&&s.status==='OFFLINE')||(previous.status==='OFFLINE'&&s.status==='ONLINE'))){const transition=s.status==='ONLINE'?'RECOVERY':'OUTAGE';s.transition=transition;this.db.prepare(`INSERT INTO smp_events(guild_id,event_type,from_status,to_status,details_json,created_at) VALUES(?,?,?,?,?,?)`).run(guildId,transition,previous.status,s.status,JSON.stringify({edition:s.edition,playersOnline:s.playersOnline??null,latencyMs:s.latencyMs??null}),s.checkedAt);}this.db.prepare(`INSERT INTO smp_status(guild_id,edition,status,players_online,players_max,version,latency_ms,source,checked_at,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(guildId,s.edition,s.status,s.playersOnline??null,s.playersMax??null,s.version??null,s.latencyMs??null,s.source,s.checkedAt,raw?JSON.stringify(raw):null);}
 getConfig(guildId){return this.db.prepare(`SELECT * FROM smp_config WHERE guild_id=?`).get(guildId);}
 setConfig(guildId,cfg){if(!cfg.javaHost||!Number.isInteger(Number(cfg.javaPort))||Number(cfg.javaPort)<=0)throw new Error('Valid Java host and port are required.');this.db.prepare(`INSERT INTO smp_config(guild_id,java_host,java_port,bedrock_host,bedrock_port,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(guild_id) DO UPDATE SET java_host=excluded.java_host,java_port=excluded.java_port,bedrock_host=excluded.bedrock_host,bedrock_port=excluded.bedrock_port,updated_at=excluded.updated_at`).run(guildId,cfg.javaHost,Number(cfg.javaPort),cfg.bedrockHost||null,cfg.bedrockPort?Number(cfg.bedrockPort):null,new Date().toISOString());}
 async checkBoth(guildId){const c=this.getConfig(guildId);if(!c)return {java:{status:'NOT_CONFIGURED'},bedrock:{status:'NOT_CONFIGURED'}};return {java:await this.checkEdition(guildId,'JAVA',c.java_host,c.java_port),bedrock:c.bedrock_host?await this.checkEdition(guildId,'BEDROCK',c.bedrock_host,c.bedrock_port):{edition:'BEDROCK',status:'NOT_CONFIGURED'}};}
}
module.exports={MinecraftService,normalizeProviderResponse};
