const {RISK}=require('../../actions/engine');
const {PermissionFlagsBits}=require('discord.js');
const {NethrionError,CODES}=require('../../observability/errors');
const {redact}=require('../agent');
const tool=(name,description,schema,risk,execute)=>({name,description,parameters:schema,risk,execute});
function requireStaff(ctx){if(ctx.guild.ownerId===ctx.member.id||ctx.member.permissions.has(PermissionFlagsBits.ManageGuild)||ctx.member.permissions.has(PermissionFlagsBits.ViewAuditLog))return true;throw new NethrionError(CODES.MISSING_PERMISSION,'Staff permission required for this information.');}
function requireStaffOrSelf(ctx,userId){if(userId===ctx.member.id)return true;return requireStaff(ctx);}
function buildToolRegistry(services){return [
 tool('get_server_overview','Return current Discord guild structure, counts, mode and bot authority. Live source.',{type:'object',properties:{},additionalProperties:false},RISK.LOW,ctx=>services.discord.overview(ctx.guild)),
 tool('get_smp_status','Check current configured Java/Bedrock SMP status.',{type:'object',properties:{},additionalProperties:false},RISK.LOW,ctx=>services.minecraft.checkBoth(ctx.guild.id)),
 tool('get_effective_channel_access','Explain effective access for a user in a channel.',{type:'object',properties:{user_id:{type:'string'},channel_id:{type:'string'},permission:{type:'string'}},required:['user_id','channel_id','permission'],additionalProperties:false},RISK.LOW,ctx=>services.discord.effectiveAccess(ctx.guild,ctx.args.user_id,ctx.args.channel_id,ctx.args.permission)),
 tool('search_server_messages','Search accessible Discord history for evidence. Caller must be able to view the searched channels.',{type:'object',properties:{query:{type:'string',minLength:1,maxLength:300},channel_id:{type:'string'},limit:{type:'integer',minimum:1,maximum:100}},required:['query'],additionalProperties:false},RISK.LOW,ctx=>services.discord.searchHistory(ctx.guild,ctx.args.query,ctx.args.channel_id,ctx.args.limit||50,ctx.member)),
 tool('search_server_knowledge','Search curated NETHRION knowledge.',{type:'object',properties:{query:{type:'string',minLength:1,maxLength:300},limit:{type:'integer',minimum:1,maximum:20}},required:['query'],additionalProperties:false},RISK.LOW,ctx=>({state:'SUCCESS',source:'curated',results:services.knowledge.search(ctx.guild.id,ctx.args.query,ctx.args.limit||8)})),
 tool('get_member_memory','Return memory for the caller, or staff-authorized memory for another member.',{type:'object',properties:{user_id:{type:'string'}},additionalProperties:false},RISK.LOW,ctx=>services.memory.get(ctx.guild.id,ctx.args.user_id||ctx.member.id,ctx.member)),
 tool('get_recent_activity','Return recent analytics events for operational context.',{type:'object',properties:{days:{type:'integer',minimum:1,maximum:30}},additionalProperties:false},RISK.LOW,ctx=>({state:'SUCCESS',source:'analytics',rows:services.analytics.summary(ctx.guild.id,ctx.args.days||7)})),
 tool('get_actionable_analytics','Return actionable metrics for active members, activity, support, moderation, security and SMP outages.',{type:'object',properties:{days:{type:'integer',minimum:1,maximum:30}},additionalProperties:false},RISK.LOW,ctx=>({state:'SUCCESS',source:'analytics',data:services.analytics.actionableSummary(ctx.guild.id,ctx.args.days||7)})),
 tool('get_away_recap','Return structured meaningful events from the selected period. AI may summarize this evidence for the caller.',{type:'object',properties:{hours:{type:'integer',minimum:1,maximum:168}},additionalProperties:false},RISK.LOW,ctx=>services.recap.compact(ctx.guild.id,ctx.args.hours||24)),
 tool('get_audit_log','Return recent Discord audit entries. Staff-only.',{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:50}},additionalProperties:false},RISK.LOW,async ctx=>{requireStaff(ctx);return services.discord.audit(ctx.guild,ctx.args.limit||20);}),
 tool('get_reports','Return NETHRION reports. Staff-only.',{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:50}},additionalProperties:false},RISK.LOW,ctx=>{requireStaff(ctx);return {state:'SUCCESS',rows:services.db.prepare(`SELECT * FROM reports WHERE guild_id=? ORDER BY id DESC LIMIT ?`).all(ctx.guild.id,ctx.args.limit||20)};}),
 tool('get_security_incidents','Return grouped security incidents. Staff-only.',{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:50}},additionalProperties:false},RISK.LOW,ctx=>{requireStaff(ctx);return {state:'SUCCESS',rows:services.db.prepare(`SELECT * FROM security_incidents WHERE guild_id=? ORDER BY last_seen_at DESC LIMIT ?`).all(ctx.guild.id,ctx.args.limit||20)};}),
 tool('get_health_diagnostic','Return health states plus a compact root-cause-oriented explanation. Staff/owner only.',{type:'object',properties:{},additionalProperties:false},RISK.LOW,async ctx=>{requireStaff(ctx);const rows=await services.health.snapshot(ctx.guild);return {state:'SUCCESS',rows,diagnostic:services.health.explain(rows)};}),
 tool('get_ticket_transcript','Return a small private ticket transcript. Caller must be the ticket creator or staff.',{type:'object',properties:{channel_id:{type:'string'},limit:{type:'integer',minimum:1,maximum:50}},required:['channel_id'],additionalProperties:false},RISK.LOW,async ctx=>{const t=services.db.prepare(`SELECT * FROM tickets WHERE guild_id=? AND channel_id=?`).get(ctx.guild.id,ctx.args.channel_id);if(!t)throw new NethrionError(CODES.INVALID_TARGET,'Ticket not found.');if(t.creator_id!==ctx.member.id)requireStaff(ctx);const ch=ctx.guild.channels.cache.get(ctx.args.channel_id);if(!ch?.isTextBased?.())throw new NethrionError(CODES.INVALID_TARGET,'Ticket channel is unavailable.');const msgs=await ch.messages.fetch({limit:ctx.args.limit||30}).catch(()=>null);if(!msgs)return {state:'UNKNOWN',reason:'Ticket history could not be read.'};return {state:'SUCCESS',ticketId:t.id,channelId:ch.id,messages:[...msgs.values()].reverse().map(m=>({id:m.id,authorId:m.author.id,author:m.author.username,content:redact(m.content).slice(0,500),createdAt:m.createdAt.toISOString()}))};}),
 tool('assign_role','Assign an existing Discord role to a member through the safe action engine.',{type:'object',properties:{user_id:{type:'string'},role_query:{type:'string'}},required:['user_id','role_query'],additionalProperties:false},RISK.MEDIUM,ctx=>services.actions.assignRole(ctx)),
 tool('lock_channel','Restrict Send Messages for the selected channel.',{type:'object',properties:{channel_id:{type:'string'}},required:['channel_id'],additionalProperties:false},RISK.HIGH,ctx=>services.actions.lockChannel(ctx)),
 tool('unlock_channel','Restore Send Messages in the selected channel.',{type:'object',properties:{channel_id:{type:'string'}},required:['channel_id'],additionalProperties:false},RISK.HIGH,ctx=>services.actions.unlockChannel(ctx)),
 tool('delete_channel','Delete a Discord channel. Exact target and confirmation required.',{type:'object',properties:{channel_id:{type:'string'}},required:['channel_id'],additionalProperties:false},RISK.CRITICAL,ctx=>services.actions.deleteChannel(ctx)),
 tool('open_ticket','Open a private support ticket for the caller.',{type:'object',properties:{},additionalProperties:false},RISK.LOW,ctx=>services.tickets.open(ctx.guild,ctx.member).then(c=>({state:'SUCCESS',channelId:c.id}))),
 tool('create_report','Create a member report.',{type:'object',properties:{target_user_id:{type:'string'},reason:{type:'string',minLength:3,maxLength:2000}},required:['target_user_id','reason'],additionalProperties:false},RISK.MEDIUM,ctx=>{const target=ctx.guild.members.cache.get(ctx.args.target_user_id);if(!target)throw new NethrionError(CODES.INVALID_TARGET,'Report target is not a current server member.');const now=new Date().toISOString();const id=services.db.prepare(`INSERT INTO reports(guild_id,reporter_id,target_id,reason,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).run(ctx.guild.id,ctx.member.id,target.id,ctx.args.reason,'OPEN',now,now).lastInsertRowid;services.analytics.event(ctx.guild.id,'report_created',String(id),{targetId:target.id});services.repos.addAudit({guildId:ctx.guild.id,actionId:`report:${id}`,actorId:ctx.member.id,request:ctx.request,resolvedIntent:'report',toolName:'create_report',target:{targetId:target.id},resultState:'SUCCESS'});return {state:'SUCCESS',message:'Report submitted privately.',reportId:id};}),
 tool('create_suggestion','Submit a suggestion.',{type:'object',properties:{idea:{type:'string',minLength:3,maxLength:2000}},required:['idea'],additionalProperties:false},RISK.LOW,ctx=>{const id=services.suggestions.add(ctx.guild.id,ctx.member.id,ctx.args.idea);services.analytics.event(ctx.guild.id,'suggestion_created',String(id));return {state:'SUCCESS',message:'Suggestion recorded.',suggestionId:id};}),
 tool('get_suggestion_themes','Return recent suggestions and grouped themes.',{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:50}},additionalProperties:false},RISK.LOW,ctx=>({state:'SUCCESS',recent:services.suggestions.recent(ctx.guild.id,ctx.args.limit||20),groups:services.suggestions.groups(ctx.guild.id)})),
 tool('create_backup','Create a manifest-backed NETHRION backup.',{type:'object',properties:{},additionalProperties:false},RISK.MEDIUM,ctx=>{requireStaff(ctx);return services.backups.create(ctx.guild,ctx.member.id);}),
 tool('health_check','Return structured subsystem health.',{type:'object',properties:{},additionalProperties:false},RISK.LOW,async ctx=>{requireStaff(ctx);return services.health.snapshot(ctx.guild);}),
 tool('remember','Save a small user-scoped preference or fact with provenance and optional expiry.',{type:'object',properties:{content:{type:'string',minLength:1,maxLength:500},type:{type:'string',maxLength:40},expires_at:{type:'string',maxLength:40}},required:['content'],additionalProperties:false},RISK.LOW,ctx=>services.memory.save(ctx.guild.id,ctx.member.id,ctx.args.type||'preference',ctx.args.content,'explicit',.8,ctx.args.expires_at||null)),
 tool('forget_memory','Remove the caller memory or staff-authorized memory for another member.',{type:'object',properties:{user_id:{type:'string'}},additionalProperties:false},RISK.MEDIUM,ctx=>{const userId=ctx.args.user_id||ctx.member.id;requireStaffOrSelf(ctx,userId);services.db.prepare(`DELETE FROM memory_facts WHERE guild_id=? AND subject_id=?`).run(ctx.guild.id,userId);return {state:'SUCCESS',message:'Stored memory removed.'};}),
 tool('schedule_reminder','Schedule a one-time message in the current or selected accessible channel.',{type:'object',properties:{delay:{type:'string'},message:{type:'string',minLength:1,maxLength:1500},channel_id:{type:'string'}},required:['delay','message'],additionalProperties:false},RISK.LOW,ctx=>{if(!/^\d+[smhd]$/i.test(ctx.args.delay))throw new NethrionError(CODES.INVALID_TOOL_ARGS,'Delay must look like 10m, 2h, or 1d.');const channelId=ctx.args.channel_id||ctx.message.channel.id;const ch=ctx.guild.channels.cache.get(channelId);if(!ch?.isTextBased?.()||!ch.permissionsFor(ctx.member)?.has(PermissionFlagsBits.ViewChannel))throw new NethrionError(CODES.CHANNEL_ACCESS_DENIED,'That channel is not accessible to you.');const id=services.scheduler.create({guildId:ctx.guild.id,ownerId:ctx.member.id,type:'send_message',payload:{channelId,content:ctx.args.message},schedule:`in:${ctx.args.delay}`,timezone:services.repos.getGuildSettings(ctx.guild.id)?.timezone||'Asia/Karachi',idempotencyKey:`reminder:${ctx.guild.id}:${ctx.member.id}:${Date.now()}`});return {state:'SUCCESS',message:`Reminder #${id} scheduled.`};}),
 tool('get_server_relations','Return stored NETHRION relation edges for a known object.',{type:'object',properties:{from_type:{type:'string'},from_id:{type:'string'}},required:['from_type','from_id'],additionalProperties:false},RISK.LOW,ctx=>({state:'SUCCESS',source:'nethrion-db-relations',relations:services.knowledge.relations(ctx.guild.id,ctx.args.from_type,ctx.args.from_id)})),
 tool('add_knowledge','Add a curated knowledge record. Staff-only.',{type:'object',properties:{category:{type:'string',maxLength:80},title:{type:'string',minLength:1,maxLength:200},body:{type:'string',minLength:1,maxLength:5000}},required:['category','title','body'],additionalProperties:false},RISK.MEDIUM,ctx=>{requireStaff(ctx);const id=services.knowledge.add(ctx.guild.id,{category:ctx.args.category,title:ctx.args.title,body:ctx.args.body,source:'staff',editorId:ctx.member.id});return {state:'SUCCESS',message:'Knowledge record added.',knowledgeId:id};}),
 tool('set_server_mode','Change NETHRION server mode. Manage Server or owner required.',{type:'object',properties:{mode:{type:'string',enum:['NORMAL','EVENT','MAINTENANCE','SMP_MAINTENANCE','RAID_PROTECTION','EMERGENCY']}},required:['mode'],additionalProperties:false},RISK.HIGH,ctx=>services.actions.setServerMode(ctx))
];}
module.exports={buildToolRegistry,requireStaff};
