const {Client,GatewayIntentBits,Events,ActionRowBuilder,ButtonBuilder,ButtonStyle,EmbedBuilder,PermissionFlagsBits}=require('discord.js');
const {loadConfig}=require('../config/config');const {createLogger}=require('../observability/logger');const {buildServices}=require('./services');
const {buildCommands}=require('../discord/commands');const {actionPreview,actionButtons,safeText,normalizeAiReply,formatToolResult,formatOverview,formatSmp,formatHealth,formatAnalytics,formatRecap,formatControl}=require('../ui/formatters');
const config=loadConfig();const logger=createLogger(process.env.LOG_LEVEL||'info');if(!config.discordToken)logger.warn('DISCORD_TOKEN is not configured; bot will not connect.');
const services=buildServices(config,logger);
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildVoiceStates,GatewayIntentBits.GuildPresences]});
services._client=client;
services.panels.attachClient(client);
function publicError(e){const msg=String(e?.message||e);return msg.length>500?msg.slice(0,497)+'...':msg;}
async function replyAction(interaction,result){
 if(result.state==='BLOCKED'&&result.code==='CONFIRMATION_REQUIRED')return interaction.reply({embeds:[actionPreview(result)],components:[actionButtons(result.actionId)],ephemeral:true});
 if(result.state==='SUCCESS'){const toolName=result.plan?.toolName;return interaction.reply({content:safeText(result.message||formatToolResult(toolName,result.result||result)||'Action completed and verified.'),ephemeral:true,allowedMentions:{parse:[]}});}
 return interaction.reply({content:safeText(result.message||`Action ${result.code||'failed'}.`),ephemeral:true,allowedMentions:{parse:[]}});
}
async function replyAgent(target,result,{ephemeral=false}={}){
 if(result?.actionPreview){const preview={state:'BLOCKED',code:'CONFIRMATION_REQUIRED',actionId:result.actionPreview.actionId,plan:result.actionPreview.plan,expiresAt:result.actionPreview.expiresAt};return target.reply({content:safeText(result.reply||'Action preview ready.'),embeds:[actionPreview(preview)],components:[actionButtons(result.actionPreview.actionId)],ephemeral,allowedMentions:{parse:[]}});}
 return target.reply({content:normalizeAiReply(result?.reply||'No response.'),ephemeral,allowedMentions:{parse:[]}});
}
async function report(guild,member,targetId,reason){const now=new Date().toISOString();const id=services.db.prepare(`INSERT INTO reports(guild_id,reporter_id,target_id,reason,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).run(guild.id,member.id,targetId,reason,'OPEN',now,now).lastInsertRowid;services.analytics.event(guild.id,'report_created',String(id),{targetId});services.repos.addAudit({guildId:guild.id,actionId:`report:${id}`,actorId:member.id,request:'create report',resolvedIntent:'report',toolName:'create_report',target:{targetId},resultState:'SUCCESS'});return id;}
async function handleNethrionCommand(i){const guild=i.guild;const member=await guild.members.fetch(i.user.id);const sub=i.options.getSubcommand();const ctx={guild,member,message:i,request:`/nethrion ${sub}`};
 if(sub==='ask'){await i.deferReply({ephemeral:true});const r=await services.agent.run({message:i,guild,member,text:i.options.getString('question',true)});if(r.actionPreview){const preview={state:'BLOCKED',code:'CONFIRMATION_REQUIRED',actionId:r.actionPreview.actionId,plan:r.actionPreview.plan,expiresAt:r.actionPreview.expiresAt};return i.editReply({content:safeText(r.reply),embeds:[actionPreview(preview)],components:[actionButtons(r.actionPreview.actionId)],allowedMentions:{parse:[]}});}return i.editReply({content:normalizeAiReply(r.reply),allowedMentions:{parse:[]}});}
 if(sub==='smp'){const r=await services.minecraft.checkBoth(guild.id);return i.reply({content:formatSmp(r),allowedMentions:{parse:[]}});}
 if(sub==='ip'){const c=services.minecraft.getConfig(guild.id);return i.reply({content:`Java: \`${c?.java_host||config.defaultJavaHost}:${c?.java_port||config.defaultJavaPort}\`\nBedrock: \`${c?.bedrock_host||config.defaultBedrockHost}:${c?.bedrock_port||config.defaultBedrockPort}\``,ephemeral:true,allowedMentions:{parse:[]}});}
 if(sub==='health'||sub==='diagnose'){if(guild.ownerId!==member.id&&!member.permissions.has(PermissionFlagsBits.ManageGuild)&&!member.permissions.has(PermissionFlagsBits.ViewAuditLog))return i.reply({content:'Staff permission required.',ephemeral:true});const rows=await services.health.snapshot(guild);return i.reply({content:formatHealth(rows),ephemeral:sub==='diagnose',allowedMentions:{parse:[]}});}
 if(sub==='overview')return i.reply({content:formatOverview(services.discord.overview(guild)),ephemeral:true,allowedMentions:{parse:[]}});
 if(sub==='recap'){const data=services.recap.compact(guild.id,i.options.getInteger('hours')||24);return i.reply({content:formatRecap(data),allowedMentions:{parse:[]}});}
 if(sub==='analytics'){const rows=services.analytics.summary(guild.id,i.options.getInteger('days')||7);return i.reply({content:formatAnalytics(rows,i.options.getInteger('days')||7),ephemeral:true,allowedMentions:{parse:[]}});}
 if(sub==='ticket'){const c=await services.tickets.open(guild,member);return i.reply({content:`Ticket: <#${c.id}>`,ephemeral:true});}
 if(sub==='close-ticket'){const r=await services.tickets.close(guild,i.channel.id,member.id);return i.reply({content:r.closed?'Ticket closed.':'This channel is not an open NETHRION ticket.',ephemeral:true});}
 if(sub==='suggest'){const id=services.suggestions.add(guild.id,member.id,i.options.getString('idea',true));services.analytics.event(guild.id,'suggestion_created',String(id));return i.reply({content:`Suggestion #${id} recorded.`,ephemeral:true});}
 if(sub==='report'){const id=await report(guild,member,i.options.getUser('user',true).id,i.options.getString('reason',true));return i.reply({content:`Report #${id} submitted privately.`,ephemeral:true});}
 if(sub==='role'){return replyAction(i,await services.actions.assignRole({...ctx,args:{user_id:i.options.getUser('user',true).id,role_query:i.options.getString('role',true)}}));}
 if(sub==='lock')return replyAction(i,await services.actions.lockChannel({...ctx,args:{channel_id:i.channel.id}}));
 if(sub==='unlock')return replyAction(i,await services.actions.unlockChannel({...ctx,args:{channel_id:i.channel.id}}));
 if(sub==='purge')return replyAction(i,await services.actions.purgeMessages({...ctx,args:{channel_id:i.channel.id,amount:i.options.getInteger('amount',true)}}));
 if(sub==='backup'){if(!member.permissions.has(PermissionFlagsBits.ManageGuild)&&guild.ownerId!==member.id)return i.reply({content:'Manage Server permission required.',ephemeral:true});const b=await services.backups.create(guild,member.id);services.analytics.event(guild.id,'backup_created',String(b.id));return i.reply({content:`Backup #${b.id} created and checksumed.`,ephemeral:true});}
 if(sub==='mode'){return replyAction(i,await services.actions.setServerMode({...ctx,args:{mode:i.options.getString('mode',true)}}));}
 if(sub==='undo'){return i.reply({content:(await services.actions.undo({...ctx},i.options.getString('action_id',true))).message||'Undo finished.',ephemeral:true});}
 if(sub==='control'){if(guild.ownerId!==member.id)return i.reply({content:'Owner access required.',ephemeral:true});const s=services.repos.getGuildSettings(guild.id)||{};return i.reply({content:formatControl(s,{geminiConfigured:services.ai.configured,groqConfigured:services.ai.groqConfigured}),ephemeral:true,allowedMentions:{parse:[]}});}
 return i.reply({content:'Unsupported NETHRION operation.',ephemeral:true});
}
async function handleLegacyPrefix(message){if(message.author.bot||!message.guild)return false;const m=message.content.trim().match(/^(?:sp|s)\s+([\s\S]+)$/i);if(!m)return false;const raw=m[1].trim();const [cmd,...rest]=raw.split(/\s+/);const sub=cmd.toLowerCase();const guild=message.guild;const member=message.member;const ctx={guild,member,message,request:message.content,args:{}};
 if(sub==='help'){
  const isAdmin=Boolean(guild.ownerId===member.id||member.permissions.has(PermissionFlagsBits.Administrator));
  if(rest[0]?.toLowerCase()==='admin'){
   if(!isAdmin)return message.reply('Admin permission required.');
   const publicHelp=[
    '`sp smp` — check the configured NETHRION SMP status.',
    '`sp ip` — show Java/Bedrock IP and port details.',
    '`sp ticket` — open a private support ticket.',
    '`sp streak [@user]` — view an activity streak.',
    '`sp board` — view the streak leaderboard.',
    '`sp suggest <idea>` — submit a community suggestion.',
    '`sp report @user <reason>` — privately report a member.',
    '`sp ask <question>` — ask the NETHRION AI brain.',
    '`sp profile [@user]` — view a member summary.'
   ].join('\n');
   const staffHelp=[
    '`sp role @user <role>` — assign a role (Manage Roles).',
    '`sp rolelist` — list server roles.',
    '`sp lock` / `sp unlock` — lock/unlock the current channel.',
    '`sp purge <1-100>` — delete recent messages.',
    '`sp task <duration> <message>` — schedule a message.',
    '`sp summary` / `sp recap` — recent community activity.',
    '`sp cases` — view recent reports/cases.',
    '`sp backups` — list recent backups.'
   ].join('\n');
   const adminHelp=[
    '`sp smp-set <javaHost> <javaPort> [bedrockHost] [bedrockPort]` — configure SMP.',
    '`sp smp-panel` — SMP panel setup.',
    '`sp yt-setup <channel-id>` — YouTube alert configuration.',
    '`sp roles-panel` — notification role panel setup.',
    '`sp link <minecraft-name>` — link a Minecraft account.',
    '`sp diagnose` — server health/diagnostics.',
    '`sp backup` — create a server backup.',
    '`sp control` — owner control information.',
    '`sp mode <mode>` — change NETHRION server mode.',
    '`sp undo <action-id>` — attempt to undo an eligible action.'
   ].join('\n');
   return message.reply({embeds:[new EmbedBuilder().setTitle('NETHRION Admin Commands').setDescription('Complete `sp` command reference.').addFields({name:'Member',value:publicHelp},{name:'Staff',value:staffHelp},{name:'Admin / Owner',value:adminHelp}).setFooter({text:'NETHRION operations'})]});
  }
  return message.reply({embeds:[new EmbedBuilder().setTitle('NETHRION Commands').setDescription('Common commands you can use.').addFields({name:'Member Commands',value:[
   '`sp smp` — Minecraft server status',
   '`sp ip` — Minecraft IP details',
   '`sp ticket` — open a private ticket',
   '`sp streak [@user]` — streak profile',
   '`sp board` — streak leaderboard',
   '`sp suggest <idea>` — submit a suggestion',
   '`sp report @user <reason>` — private report',
   '`sp ask <question>` — ask NETHRION AI',
   '`sp profile [@user]` — member summary'
  ].join('\n')},{name:'More',value:'Use `sp help admin` for the staff/admin command list.'}).setFooter({text:'NETHRION operations'})]});
 }
 if(sub==='smp'){const r=await services.minecraft.checkBoth(guild.id);return message.reply({content:formatSmp(r),allowedMentions:{parse:[]}});}
 if(sub==='ip'){const c=services.minecraft.getConfig(guild.id);return message.reply(`Java: ${c?.java_host||config.defaultJavaHost}:${c?.java_port||25565}\nBedrock: ${c?.bedrock_host||config.defaultBedrockHost}:${c?.bedrock_port||26091}`);}
 if(sub==='ticket'){const c=await services.tickets.open(guild,member);return message.reply(`Ticket opened: <#${c.id}>`);}
 if(sub==='streak'||sub==='board'){const rows=services.db.prepare(`SELECT * FROM streaks WHERE guild_id=? ORDER BY current_streak DESC LIMIT 10`).all(guild.id);if(sub==='streak'){const r=rows.find(x=>x.user_id===member.id)||{current_streak:0,highest_streak:0,total_active_days:0};return message.reply(`Current: ${r.current_streak}\nHighest: ${r.highest_streak}\nActive days: ${r.total_active_days}`);}return message.reply(rows.map((r,i)=>`${i+1}. <@${r.user_id}> — ${r.current_streak}`).join('\n')||'No streak data.');}
 if(sub==='suggest'){const id=services.suggestions.add(guild.id,member.id,rest.join(' '));services.analytics.event(guild.id,'suggestion_created',String(id));return message.reply(`Suggestion #${id} recorded.`);}
 if(sub==='report'){const target=message.mentions.users.first();const reason=rest.filter(x=>!/^<@!?\d+>$/.test(x)).join(' ');if(!target||!reason)return message.reply('Usage: sp report @user <reason>');await report(guild,member,target.id,reason);return message.reply('Report submitted privately.');}
 if(sub==='role'){const target=message.mentions.users.first();const roleQuery=rest.filter(x=>!/^<@!?\d+>$/.test(x)).join(' ');if(!target||!roleQuery)return message.reply('Usage: sp role @user <role>');const r=await services.actions.assignRole({...ctx,args:{user_id:target.id,role_query:roleQuery}});return message.reply({content:safeText(r.state==='SUCCESS'?'Role added.':r.message||`Action ${r.code||'failed'}.`),allowedMentions:{parse:[]}});}
 if(sub==='rolelist'){const roles=[...guild.roles.cache.values()].filter(r=>!r.managed).sort((a,b)=>b.position-a.position).slice(0,50);return message.reply({content:roles.length?`**Server roles (${roles.length})**\n${roles.map(r=>`• ${safeText(r.name,80)}`).join('\n')}`:'No roles.',allowedMentions:{parse:[]}});}
 if(['lock','unlock','slock','sunlock'].includes(sub)){const lock=!['unlock','sunlock'].includes(sub);const r=await services.actions[lock?'lockChannel':'unlockChannel']({...ctx,args:{channel_id:message.channel.id}});if(r.state==='BLOCKED'&&r.code==='CONFIRMATION_REQUIRED')return message.reply({content:'Action preview ready.',embeds:[actionPreview(r)],components:[actionButtons(r.actionId)],allowedMentions:{parse:[]}});return message.reply(r.state==='SUCCESS'?'Channel updated.':r.message||`Action ${r.code||'failed'}.`);}
 if(sub==='purge'){const amount=Number(rest[0]);if(!Number.isInteger(amount)||amount<1||amount>100)return message.reply('Usage: sp purge <1-100>');const r=await services.actions.purgeMessages({...ctx,args:{channel_id:message.channel.id,amount}});if(r.state==='BLOCKED'&&r.code==='CONFIRMATION_REQUIRED')return message.reply({content:'Action preview ready.',embeds:[actionPreview(r)],components:[actionButtons(r.actionId)],allowedMentions:{parse:[]}});return message.reply(r.message||`Purge ${r.code||'failed'}.`);}
 if(sub==='task'){const [duration,...text]=rest;const job=services.scheduler.create({guildId:guild.id,ownerId:member.id,type:'send_message',payload:{channelId:message.channel.id,content:text.join(' ')||'Scheduled NETHRION reminder.'},schedule:duration?.match(/^\d+[smhd]$/i)?`in:${duration}`:duration,timezone:config.timezone});return message.reply(`Task #${job} scheduled.`);}
 if(sub==='summary'||sub==='recap'){const d=services.recap.compact(guild.id,24);return message.reply({content:formatRecap(d),allowedMentions:{parse:[]}});}
 if(sub==='cases'){if(guild.ownerId!==member.id&&!member.permissions.has(PermissionFlagsBits.ManageGuild))return message.reply('Staff permission required.');const rows=services.db.prepare(`SELECT id,target_id,reason,status,created_at FROM reports WHERE guild_id=? ORDER BY id DESC LIMIT 20`).all(guild.id);return message.reply(rows.map(r=>`#${r.id} <@${r.target_id||'0'}> ${r.status}: ${r.reason}`).join('\n')||'No reports.');}
 if(sub==='smp-set'){if(guild.ownerId!==member.id&&!member.permissions.has(PermissionFlagsBits.ManageGuild))return message.reply('Manage Server permission required.');const [jh,jp,bh,bp]=rest;if(!jh||!jp)return message.reply('Usage: sp smp-set <javaHost> <javaPort> [bedrockHost] [bedrockPort]');services.minecraft.setConfig(guild.id,{javaHost:jh,javaPort:Number(jp),bedrockHost:bh,bedrockPort:bp?Number(bp):null});services.panels.update(guild.id,'smp').catch(()=>{});services.repos.addAudit({guildId:guild.id,actionId:`smp-config:${Date.now()}`,actorId:member.id,request:message.content,resolvedIntent:'set SMP configuration',toolName:'smp_set',target:{javaHost:jh,bedrockHost:bh||null},resultState:'SUCCESS'});return message.reply('SMP configuration updated.');}
 if(sub==='link'){const ign=rest.join(' ');if(!ign)return message.reply('Usage: sp link <minecraft name>');services.db.prepare(`INSERT OR REPLACE INTO minecraft_links(guild_id,discord_id,minecraft_name,created_by,created_at) VALUES(?,?,?,?,?)`).run(guild.id,member.id,ign,member.id,new Date().toISOString());services.repos.addAudit({guildId:guild.id,actionId:`link:${member.id}`,actorId:member.id,request:message.content,resolvedIntent:'link Minecraft account',toolName:'link_minecraft',target:{discordId:member.id},resultState:'SUCCESS'});return message.reply(`Linked Minecraft account: ${ign}`);}
 if(sub==='backups'){if(guild.ownerId!==member.id&&!member.permissions.has(PermissionFlagsBits.ManageGuild)&&!member.permissions.has(PermissionFlagsBits.ViewAuditLog))return message.reply('Staff permission required.');return message.reply(services.backups.list(guild.id).map(b=>`#${b.id} ${b.created_at} ${b.checksum.slice(0,12)}`).join('\n')||'No backups.');}
 if(sub==='diagnose'){if(guild.ownerId!==member.id&&!member.permissions.has(PermissionFlagsBits.ManageGuild)&&!member.permissions.has(PermissionFlagsBits.ViewAuditLog))return message.reply('Staff permission required.');const rows=await services.health.snapshot(guild);return message.reply({content:formatHealth(rows),allowedMentions:{parse:[]}});}
 if(sub==='ask'){const q=rest.join(' ');if(!q)return message.reply('Usage: sp ask <question>');const r=await services.agent.run({message,guild,member,text:q});return replyAgent(message,r);}
 if(sub==='profile'){const t=message.mentions.members.first()||member;return message.reply({content:`**${safeText(t.user.username,80)}**\nRoles: ${t.roles.cache.filter(r=>r.id!==guild.id).map(r=>safeText(r.name,80)).join(', ')||'none'}`,allowedMentions:{parse:[]}});}
 if(sub==='yt-setup'){if(guild.ownerId!==member.id&&!member.permissions.has(PermissionFlagsBits.ManageGuild))return message.reply('Manage Server permission required.');services.repos.updateGuildSettings(guild.id,{channels:{...(services.repos.getGuildSettings(guild.id)?.channels||{}),youtubeChannelId:rest[0]||null}});return message.reply('YouTube configuration stored. Alert delivery remains disabled until the feature is enabled.');}
 if(['smp-panel','ticket-panel','roles-panel','anon-panel'].includes(sub))return services.panels.handleCommand(message,sub.replace('-panel',''));
 if(sub==='image')return message.reply(config.features.image?'Image generation is configured as a gated feature; no public auto-generation route is enabled yet.':'Image generation is disabled.');
 return false;
}
client.once(Events.ClientReady,async c=>{logger.info(`Logged in as ${c.user.tag}`);for(const guild of c.guilds.cache.values()){try{services.discord.syncGuild(guild);const s=services.repos.getGuildSettings(guild.id);if(!s?.featureFlags||!Object.keys(s.featureFlags).length)services.repos.updateGuildSettings(guild.id,{featureFlags:config.features});services.knowledge.seedDefaults(guild.id);if(!services.minecraft.getConfig(guild.id))services.minecraft.setConfig(guild.id,{javaHost:config.defaultJavaHost,javaPort:config.defaultJavaPort,bedrockHost:config.defaultBedrockHost,bedrockPort:config.defaultBedrockPort});if(!services.db.prepare(`SELECT 1 FROM scheduled_jobs WHERE guild_id=? AND type='smp_monitor' AND status='ACTIVE' LIMIT 1`).get(guild.id))services.scheduler.create({guildId:guild.id,ownerId:guild.ownerId,type:'smp_monitor',payload:{},schedule:'every:60s',timezone:config.timezone,idempotencyKey:`smp-monitor:${guild.id}`});}catch(e){logger.error('Guild bootstrap failed',guild.id,e);}}
 services.scheduler.register('send_message',async job=>{const guild=c.guilds.cache.get(job.guild_id);const channel=guild?.channels.cache.get(job.payload.channelId);if(!channel?.isTextBased?.())throw new Error('Scheduled channel unavailable.');await channel.send({content:String(job.payload.content||'Scheduled NETHRION reminder.'),allowedMentions:{parse:[]}});services.analytics.event(guild.id,'scheduled_message_sent',job.owner_id);});
 services.scheduler.register('smp_monitor',async job=>{const guild=c.guilds.cache.get(job.guild_id);if(!guild)return;const r=await services.minecraft.checkBoth(guild.id);const settings=services.repos.getGuildSettings(guild.id);const alertId=settings?.channels?.smpAlertChannelId;const ch=alertId?guild.channels.cache.get(alertId):null;for(const [key,status] of Object.entries(r)){if(!status.transition||!ch?.isTextBased?.())continue;const text=status.transition==='OUTAGE'?`SMP ${key} is offline.`:`SMP ${key} recovered.`;await ch.send({content:text,allowedMentions:{parse:[]}}).catch(()=>{});}}); services.scheduler.register('discord_reconcile',async job=>{const guild=c.guilds.cache.get(job.guild_id);if(guild)services.discord.reconcileGuild(guild);});
 for(const guild of c.guilds.cache.values()){if(!services.db.prepare(`SELECT 1 FROM scheduled_jobs WHERE guild_id=? AND type='discord_reconcile' AND status='ACTIVE' LIMIT 1`).get(guild.id))services.scheduler.create({guildId:guild.id,ownerId:guild.ownerId,type:'discord_reconcile',payload:{},schedule:'every:15m',timezone:config.timezone,idempotencyKey:`discord-reconcile:${guild.id}`});}

 services.scheduler.start();services.dashboard.start();setInterval(()=>services.panels.refreshAllSmpPanels().catch(()=>{}),60000);setTimeout(()=>services.panels.refreshAllSmpPanels().catch(()=>{}),5000);});
client.on(Events.GuildMemberAdd,async member=>{services.repos.upsertMember(member.guild.id,{id:member.id,username:member.user.username,displayName:member.displayName,roleIds:[...member.roles.cache.keys()],joinedAt:member.joinedAt?.toISOString(),lastSeenAt:new Date().toISOString()});services.analytics.event(member.guild.id,'member_joined',member.id);const inc=services.moderation.observeJoin(member.guild.id,member.id);if(inc.created){const s=services.repos.getGuildSettings(member.guild.id);const ch=s?.channels?.alertChannelId?member.guild.channels.cache.get(s.channels.alertChannelId):null;if(ch?.isTextBased?.())ch.send({content:'Security alert: unusual join burst detected.',allowedMentions:{parse:[]}}).catch(()=>{});}await services.onboarding.handle(member);});
client.on(Events.GuildMemberRemove,m=>services.analytics.event(m.guild.id,'member_left',m.id));
client.on(Events.GuildRoleCreate,r=>services.repos.upsertRole(r.guild.id,{id:r.id,name:r.name,position:r.position,managed:r.managed,permissions:r.permissions.toArray()}));client.on(Events.GuildRoleUpdate,(a,r)=>services.repos.upsertRole(r.guild.id,{id:r.id,name:r.name,position:r.position,managed:r.managed,permissions:r.permissions.toArray()}));client.on(Events.GuildRoleDelete,r=>services.db.prepare(`DELETE FROM roles_index WHERE guild_id=? AND role_id=?`).run(r.guild.id,r.id));
client.on(Events.ChannelCreate,ch=>services.repos.upsertChannel(ch.guild.id,{id:ch.id,name:ch.name,type:ch.type,parentId:ch.parentId,position:ch.position}));client.on(Events.ChannelUpdate,(a,ch)=>services.repos.upsertChannel(ch.guild.id,{id:ch.id,name:ch.name,type:ch.type,parentId:ch.parentId,position:ch.position}));client.on(Events.ChannelDelete,ch=>services.db.prepare(`DELETE FROM channels_index WHERE guild_id=? AND channel_id=?`).run(ch.guild.id,ch.id));
client.on(Events.MessageCreate,async message=>{try{if(await handleLegacyPrefix(message))return;if(!message.guild||message.author.bot)return;services.analytics.event(message.guild.id,'message',message.channel.id);if(config.features.moderation){const inc=services.moderation.observeMessage(message);if(inc.created){const s=services.repos.getGuildSettings(message.guild.id);const ch=s?.channels?.alertChannelId?message.guild.channels.cache.get(s.channels.alertChannelId):null;if(ch?.isTextBased?.())ch.send({content:`Security alert: ${inc.incidentKey} detected.`,allowedMentions:{parse:[]}}).catch(()=>{});}}const mentioned=message.mentions.has(client.user?.id);const settings=services.repos.getGuildSettings(message.guild.id);const aiAllowed=settings?.featureFlags?.naturalActions!==false;const allowedChannel=config.aiPublicChannels.length?config.aiPublicChannels.includes(message.channel.id):true;if(config.publicAiEnabled&&aiAllowed&&config.aiRequireMention&&mentioned&&allowedChannel){const text=message.content.replace(new RegExp(`<@!?${client.user.id}>`,'g'),'').trim();if(text){const r=await services.agent.run({message,guild:message.guild,member:message.member,text});await replyAgent(message,r);}}}catch(e){logger.error('message handler',e);}});
client.on(Events.InteractionCreate,async i=>{try{if(i.customId?.startsWith('nethrion_panel:')){const handled=await services.panels.handleInteraction(i,services);if(handled)return;}if(i.isButton()){const [type,id]=i.customId.split(':');if(type==='nethrion_cancel'){services.db.prepare(`UPDATE action_plans SET status='CANCELLED' WHERE action_id=? AND actor_id=?`).run(id,i.user.id);return i.update({content:'Action cancelled.',embeds:[],components:[]});}if(type==='nethrion_confirm'){const p=services.db.prepare(`SELECT * FROM action_plans WHERE action_id=? AND actor_id=?`).get(id,i.user.id);if(!p)return i.update({content:'This action is no longer available.',embeds:[],components:[]});const plan=JSON.parse(p.plan_json);const member=await i.guild.members.fetch(i.user.id);const ctx={guild:i.guild,member,message:i,request:`confirmation:${id}`,args:plan.args,actionId:id,confirm:true};let result;if(plan.toolName==='lock_channel')result=await services.actions.lockChannel(ctx);else if(plan.toolName==='unlock_channel')result=await services.actions.unlockChannel(ctx);else if(plan.toolName==='delete_channel')result=await services.actions.deleteChannel(ctx);else if(plan.toolName==='purge_messages')result=await services.actions.purgeMessages(ctx);else if(plan.toolName==='set_server_mode')result=await services.actions.setServerMode(ctx);else return i.update({content:'This action cannot be confirmed from this control.',embeds:[],components:[]});return i.update({content:result.state==='SUCCESS'?formatToolResult(plan.toolName,result.result||result):result.message||`Action ${result.code||'failed'}.`,embeds:[],components:[],allowedMentions:{parse:[]}});}}
 if(i.isChatInputCommand()&&i.commandName==='nethrion')return handleNethrionCommand(i);}catch(e){logger.error('interaction',e);if(!i.replied&&!i.deferred)await i.reply({content:publicError(e),ephemeral:true}).catch(()=>{});}});
process.on('SIGTERM',async()=>{services.dashboard.stop();services.scheduler.stop();services.db.close();client.destroy();});process.on('SIGINT',async()=>{services.dashboard.stop();services.scheduler.stop();services.db.close();client.destroy();});process.on('unhandledRejection',e=>logger.error('unhandled rejection',e));process.on('uncaughtException',e=>logger.error('uncaught exception',e));
if(require.main===module&&config.discordToken)client.login(config.discordToken).catch(e=>{logger.error('Discord login failed',e);process.exitCode=1;});
module.exports={client,services,config};
