const {NethrionDB}=require('../storage/db');
const {Repositories}=require('../storage/repos');
const {DiscordService}=require('../discord/service');
const permissions=require('../permissions/engine');
const {ActionEngine}=require('../actions/engine');
const {DiscordActionService}=require('../actions/discord-actions');
const {KnowledgeService}=require('../knowledge/service');
const {MinecraftService}=require('../minecraft/status');
const {AnalyticsService}=require('../analytics/service');
const {SchedulerService}=require('../scheduler/service');
const {TicketService}=require('../tickets/service');
const {SuggestionService}=require('../suggestions/service');
const {ModerationService}=require('../moderation/service');
const {BackupService}=require('../backups/service');
const {HealthService}=require('../health/service');
const {GeminiProvider}=require('../ai/providers/gemini');
const {GroqProvider}=require('../ai/providers/groq');
const {AIRouter}=require('../ai/router');
const {buildToolRegistry}=require('../ai/tools/registry');
const {Agent}=require('../ai/agent');
const {MemoryService}=require('../memory/service');
const {OnboardingService}=require('../onboarding/service');
const {DashboardServer}=require('../dashboard/server');
const {RecapService}=require('../recap/service');
const {PanelService}=require('../panels/service');

function buildServices(config,logger){
  const db=new NethrionDB(config.databasePath);db.migrate();const repos=new Repositories(db);
  const discord=new DiscordService({repos,logger,config});
  const minecraft=new MinecraftService({config,db,logger});
  const analytics=new AnalyticsService({db});
  const scheduler=new SchedulerService({db,logger});
  const tickets=new TicketService({db,logger});
  const suggestions=new SuggestionService({db});
  const moderation=new ModerationService({db,logger});
  const backups=new BackupService({db,config,logger});
  const gemini=new GeminiProvider({apiKey:config.geminiKey,model:config.geminiModel,logger});
  const groq=new GroqProvider({apiKey:config.groqKey,model:config.groqModel||'openai/gpt-oss-20b',logger});
  const ai=new AIRouter({gemini,groq,config,db,logger});
  const health=new HealthService({db,repos,config,ai,minecraft,scheduler});
  const knowledge=new KnowledgeService({repos});
  const memory=new MemoryService({repos});
  const engine=new ActionEngine({db,repos,permissions,logger,ttlSeconds:config.actionConfirmTtlSeconds});
  const actionService=new DiscordActionService({engine,permissions,repos,analytics,logger});
  const agent=new Agent({router:ai,toolRegistry:[],repos,config,logger});
  const onboarding=new OnboardingService({repos,logger});
  const recap=new RecapService({db});
  const panels=new PanelService({repos,minecraft,logger,config});
  const services={db,repos,discord,permissions,actions:actionService,knowledge,memory,minecraft,analytics,scheduler,tickets,suggestions,moderation,backups,health,ai,agent,onboarding,recap,panels};
  services.dashboard=new DashboardServer({config,services,logger});
  const tools=buildToolRegistry(services);agent.tools=tools;services.tools=tools;
  return services;
}
module.exports={buildServices};
